version: '3.1'

services:
  redis:
    image: redis

  app:
    image: a6543/the-federation_backend:latest
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgres://thefederation:${POSTGRES_PASSWORD:-thefederation}@db:5432/thefederation
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-topsecret}
      DJANGO_ALLOWED_HOSTS: "app"
      DJANGO_SECURE_SSL_REDIRECT: "False"
      THEFEDERATION_HTTPS: "False"
      TARGET_ENV: local
      THEFEDERATION_DOMAIN: ${THEFEDERATION_DOMAIN:-localhost}
      RQWORKER_NUM: ${RQWORKER_NUM:-1}

  web:
    image: a6543/the-federation_frontend:latest
    depends_on:
      - app
    ports:
      - "0.0.0.0:8123:80"

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-thefederation}
      POSTGRES_USER: thefederation
      POSTGRES_DB: thefederation
    volumes:
      - ./dbdata:/var/lib/postgresql/data
