branches: next

variables:
  - &platforms 'linux/amd64'

pipeline:
  frontend-dryrun:
    group: docker
    image: plugins/kaniko
    settings:
      dockerfile: docker/nginx/Dockerfile
      platforms: *platforms
      no_push: true
      repo: a6543/the-federation_frontend
      tags: test
    when:
      event: pull_request

  frontend-publish:
    group: docker
    image: plugins/kaniko
    settings:
      dockerfile: docker/nginx/Dockerfile
      platforms: *platforms
      repo: a6543/the-federation_frontend
      tags: next,v1-${CI_COMMIT_SHA:0:8}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: ["push", "tag"]
